package com.footzone.footzone.utils


object KeyValues {
    const val SMS_CODE = "smsCode"
    const val PENDING: String = "PENDING"
    const val PLAYED: String = "PLAYED"
    const val USER: String = "Oddiy foydalanuvchi"
    const val STADIUM_OWNER: String = "Maydon egasi"
    const val DEFAULT: String = "default"
    const val ADD_SUCCESS: String = "add success"
    const val DELETE_SUCCESS: String = "delete success"
    const val KEY: String = "AIzaSyCVwdU3slouglv7TBDh3juGegafJVnKx8U"
    const val DECLINED_2: String = "Rad etildi!"
    const val ACCEPTED: String = "ACCEPTED"
    const val DECLINED: String = "DECLINED"
    const val All: String = "ALL"
    const val SECURITY_KEY = "FOOTZONE_APPLICATION"
    const val NOTIFICATION_TITLE: String = "NotificationTitle"
    const val SPLASH_MESSAGE: String = "SplashMessage"
    const val STADIUM_IMAGE_BASE_URL = "https://heroku-footzone.herokuapp.com/images/stadium/"
    const val USER_IMAGE_BASE_URL = "https://heroku-footzone.herokuapp.com/images/user/"
//    const val STADIUM_IMAGE_BASE_URL = "http://192.168.43.32:8081/images/stadium/"
//    const val USER_IMAGE_BASE_URL = "http://192.168.43.32:8081/images/user/"
    const val PITCH_DETAIL: String = "pitchDetail"
    const val STADIUM_ID = "stadiumID"
    const val IS_FAVOURITE_STADIUM = "isFavouriteStadium"
    const val STADIUM_DATA = "stadiumdata"
    const val TYPE_DETAIL = "type"
    const val USER_DETAIL = "user"
    const val PHONE_NUMBER = "phoneNumber"
    var LOCATION = "location"
    const val TYPE_LOCATION = "1001"
    const val TYPE_WORK_TIME = "1002"
    const val USER_ID = "userID"
    const val USER_TOKEN = "userToken"
    const val IS_OWNER = "isOwner"
    const val LOG_IN = "LogIn"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val LANGUAGE = "language"
    const val WORK_TIMES = "workTimes"
    const val WORK_TIME = "workTime"
    const val FIREBASE_TOKEN = "Firebase Token"
    const val PICK_FROM_FILE_ADD = 1001
    const val PICK_FROM_FILE_EDIT = 1002
}